intro: |
  Git is an open source distributed version control system originally developed by Linus Torvalds to 
  support the development of the linux kernel.

guides:
  - Git/Git Overview
  - Git/Git Installation
  - Git/Getting Started with Git
  - Git/Working with a Remote Git Repository
  - Git/Contributing to an Open Source Project
  