intro: |
  Vagrant is an open source wrapper around a Virtual Machine provider, such as Oracle's 
  VirtualBox. It makes it easy to create and run a Virtual Machine (VM) from the command line.

guides:
  - "[Vagrant Overview](/Guides/Vagrant/Vagrant%20Overview)"
  - "[Vagrant Installation](/Guides/Vagrant/Vagrant%20Installation)"
  - "[Getting Started with Vagrant](/Guides/Vagrant/Getting%20Started%20with%20Vagrant)"
  - "[Known Issues](/Guides/Vagrant/Known%20Issues)"
